name: CI/CD to Render

on:
  push:
    branches: [ "main" ]   # change if your default branch is different
  workflow_dispatch:

permissions:
  contents: read
  packages: write          # needed to push to GHCR
  id-token: write

env:
  IMAGE_NAME: ghcr.io/KonstantinosNikas/todo-docker-app
  TAG_LATEST: latest
  TAG_SHA: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (latest + sha tags)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG_LATEST }}
            ${{ env.IMAGE_NAME }}:${{ env.TAG_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Optional: quick smoke test by running the image (uncomment if useful)
      # - name: Smoke test container
      #   run: |
      #     docker run -d -p 8080:8080 --name app ${{ env.IMAGE_NAME }}:${{ env.TAG_LATEST }}
      #     sleep 5
      #     docker logs app

      - name: Trigger Render Deploy
        run: |
          curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
